//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rail_Reservations
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN_LOGIN
    {
        public int ADMIN_ID { get; set; }
        public string ADMIN_NAME { get; set; }
        public string APASSWORD { get; set; }
    }
}
