//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rail_Reservations
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING_TICKETS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKING_TICKETS()
        {
            this.CANCEL_TICKET = new HashSet<CANCEL_TICKET>();
        }
    
        public int BOOK_ID { get; set; }
        public string username { get; set; }
        public int TRAINNO { get; set; }
        public string CLASSNAME { get; set; }
        public Nullable<System.DateTime> BOOKING_DATE { get; set; }
        public System.DateTime DATEOF_TRAVEL { get; set; }
        public int No_OF_TICKETS { get; set; }
        public Nullable<decimal> BOOK_AMOUNT { get; set; }
        public string Status { get; set; }
    
        public virtual TRAIN TRAIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CANCEL_TICKET> CANCEL_TICKET { get; set; }
    }
}
