//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rail_Reservations
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANCEL_TICKET
    {
        public int CANCEL_ID { get; set; }
        public System.DateTime DATE_OF_CANCEL { get; set; }
        public int TRAINNO { get; set; }
        public int NO_OF_SEATS { get; set; }
        public decimal REFUND { get; set; }
        public int BOOK_ID { get; set; }
    
        public virtual BOOKING_TICKETS BOOKING_TICKETS { get; set; }
        public virtual TRAIN TRAIN { get; set; }
    }
}
