//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rail_Reservations
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS_DETAILS
    {
        public int CLASS_ID { get; set; }
        public Nullable<int> TRAINNO { get; set; }
        public string CLASSNAME { get; set; }
        public int TOTALSEATS { get; set; }
        public int AVAILABLESEATS { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
    
        public virtual TRAIN TRAIN { get; set; }
    }
}
