//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rail_Reservations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RAIL_RESERVATIONEntities : DbContext
    {
        public RAIL_RESERVATIONEntities()
            : base("name=RAIL_RESERVATIONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN_LOGIN> ADMIN_LOGIN { get; set; }
        public virtual DbSet<BOOKING_TICKETS> BOOKING_TICKETS { get; set; }
        public virtual DbSet<CANCEL_TICKET> CANCEL_TICKET { get; set; }
        public virtual DbSet<CLASS_DETAILS> CLASS_DETAILS { get; set; }
        public virtual DbSet<TRAIN> TRAINS { get; set; }
        public virtual DbSet<USER_LOGIN> USER_LOGIN { get; set; }
    
        public virtual int ADD_CLASS_DEATILS(Nullable<int> tRAINNO, string cLASSNAME, Nullable<int> tOTALSEATS, Nullable<int> aVAILABLESEATS, Nullable<decimal> aMOUNT)
        {
            var tRAINNOParameter = tRAINNO.HasValue ?
                new ObjectParameter("TRAINNO", tRAINNO) :
                new ObjectParameter("TRAINNO", typeof(int));
    
            var cLASSNAMEParameter = cLASSNAME != null ?
                new ObjectParameter("CLASSNAME", cLASSNAME) :
                new ObjectParameter("CLASSNAME", typeof(string));
    
            var tOTALSEATSParameter = tOTALSEATS.HasValue ?
                new ObjectParameter("TOTALSEATS", tOTALSEATS) :
                new ObjectParameter("TOTALSEATS", typeof(int));
    
            var aVAILABLESEATSParameter = aVAILABLESEATS.HasValue ?
                new ObjectParameter("AVAILABLESEATS", aVAILABLESEATS) :
                new ObjectParameter("AVAILABLESEATS", typeof(int));
    
            var aMOUNTParameter = aMOUNT.HasValue ?
                new ObjectParameter("AMOUNT", aMOUNT) :
                new ObjectParameter("AMOUNT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_CLASS_DEATILS", tRAINNOParameter, cLASSNAMEParameter, tOTALSEATSParameter, aVAILABLESEATSParameter, aMOUNTParameter);
        }
    
        public virtual int ADD_CLASS_DETAILS(Nullable<int> tRAINNO, string cLASSNAME, Nullable<int> tOTALSEATS, Nullable<int> aVAILABLESEATS, Nullable<decimal> aMOUNT)
        {
            var tRAINNOParameter = tRAINNO.HasValue ?
                new ObjectParameter("TRAINNO", tRAINNO) :
                new ObjectParameter("TRAINNO", typeof(int));
    
            var cLASSNAMEParameter = cLASSNAME != null ?
                new ObjectParameter("CLASSNAME", cLASSNAME) :
                new ObjectParameter("CLASSNAME", typeof(string));
    
            var tOTALSEATSParameter = tOTALSEATS.HasValue ?
                new ObjectParameter("TOTALSEATS", tOTALSEATS) :
                new ObjectParameter("TOTALSEATS", typeof(int));
    
            var aVAILABLESEATSParameter = aVAILABLESEATS.HasValue ?
                new ObjectParameter("AVAILABLESEATS", aVAILABLESEATS) :
                new ObjectParameter("AVAILABLESEATS", typeof(int));
    
            var aMOUNTParameter = aMOUNT.HasValue ?
                new ObjectParameter("AMOUNT", aMOUNT) :
                new ObjectParameter("AMOUNT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_CLASS_DETAILS", tRAINNOParameter, cLASSNAMEParameter, tOTALSEATSParameter, aVAILABLESEATSParameter, aMOUNTParameter);
        }
    
        public virtual int ADD_TRAINS(Nullable<int> tRAINNO, string tRAINNAME, string sOURCE, string dESTINATION)
        {
            var tRAINNOParameter = tRAINNO.HasValue ?
                new ObjectParameter("TRAINNO", tRAINNO) :
                new ObjectParameter("TRAINNO", typeof(int));
    
            var tRAINNAMEParameter = tRAINNAME != null ?
                new ObjectParameter("TRAINNAME", tRAINNAME) :
                new ObjectParameter("TRAINNAME", typeof(string));
    
            var sOURCEParameter = sOURCE != null ?
                new ObjectParameter("SOURCE", sOURCE) :
                new ObjectParameter("SOURCE", typeof(string));
    
            var dESTINATIONParameter = dESTINATION != null ?
                new ObjectParameter("DESTINATION", dESTINATION) :
                new ObjectParameter("DESTINATION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_TRAINS", tRAINNOParameter, tRAINNAMEParameter, sOURCEParameter, dESTINATIONParameter);
        }
    
        public virtual int BOOK_TICKET(Nullable<int> tRAINNO, string username, string cLASSNAME, Nullable<int> nOOF_TICKETS, Nullable<System.DateTime> dATEOFTRAVEL, Nullable<decimal> bOOK_AMOUNT)
        {
            var tRAINNOParameter = tRAINNO.HasValue ?
                new ObjectParameter("TRAINNO", tRAINNO) :
                new ObjectParameter("TRAINNO", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var cLASSNAMEParameter = cLASSNAME != null ?
                new ObjectParameter("CLASSNAME", cLASSNAME) :
                new ObjectParameter("CLASSNAME", typeof(string));
    
            var nOOF_TICKETSParameter = nOOF_TICKETS.HasValue ?
                new ObjectParameter("NOOF_TICKETS", nOOF_TICKETS) :
                new ObjectParameter("NOOF_TICKETS", typeof(int));
    
            var dATEOFTRAVELParameter = dATEOFTRAVEL.HasValue ?
                new ObjectParameter("DATEOFTRAVEL", dATEOFTRAVEL) :
                new ObjectParameter("DATEOFTRAVEL", typeof(System.DateTime));
    
            var bOOK_AMOUNTParameter = bOOK_AMOUNT.HasValue ?
                new ObjectParameter("BOOK_AMOUNT", bOOK_AMOUNT) :
                new ObjectParameter("BOOK_AMOUNT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BOOK_TICKET", tRAINNOParameter, usernameParameter, cLASSNAMEParameter, nOOF_TICKETSParameter, dATEOFTRAVELParameter, bOOK_AMOUNTParameter);
        }
    
        public virtual int CANCELTICKET(Nullable<int> tRAINNO, Nullable<int> nOOFSEATS, Nullable<decimal> rEFUND, Nullable<int> bOOK_ID)
        {
            var tRAINNOParameter = tRAINNO.HasValue ?
                new ObjectParameter("TRAINNO", tRAINNO) :
                new ObjectParameter("TRAINNO", typeof(int));
    
            var nOOFSEATSParameter = nOOFSEATS.HasValue ?
                new ObjectParameter("NOOFSEATS", nOOFSEATS) :
                new ObjectParameter("NOOFSEATS", typeof(int));
    
            var rEFUNDParameter = rEFUND.HasValue ?
                new ObjectParameter("REFUND", rEFUND) :
                new ObjectParameter("REFUND", typeof(decimal));
    
            var bOOK_IDParameter = bOOK_ID.HasValue ?
                new ObjectParameter("BOOK_ID", bOOK_ID) :
                new ObjectParameter("BOOK_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CANCELTICKET", tRAINNOParameter, nOOFSEATSParameter, rEFUNDParameter, bOOK_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> BookTicket(string username, Nullable<int> tRAINNO, string cLASSNAME, Nullable<System.DateTime> dATEOF_TRAVEL, Nullable<int> no_OF_TICKETS)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var tRAINNOParameter = tRAINNO.HasValue ?
                new ObjectParameter("TRAINNO", tRAINNO) :
                new ObjectParameter("TRAINNO", typeof(int));
    
            var cLASSNAMEParameter = cLASSNAME != null ?
                new ObjectParameter("CLASSNAME", cLASSNAME) :
                new ObjectParameter("CLASSNAME", typeof(string));
    
            var dATEOF_TRAVELParameter = dATEOF_TRAVEL.HasValue ?
                new ObjectParameter("DATEOF_TRAVEL", dATEOF_TRAVEL) :
                new ObjectParameter("DATEOF_TRAVEL", typeof(System.DateTime));
    
            var no_OF_TICKETSParameter = no_OF_TICKETS.HasValue ?
                new ObjectParameter("No_OF_TICKETS", no_OF_TICKETS) :
                new ObjectParameter("No_OF_TICKETS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("BookTicket", usernameParameter, tRAINNOParameter, cLASSNAMEParameter, dATEOF_TRAVELParameter, no_OF_TICKETSParameter);
        }
    }
}
